# Generated by Django 4.1 on 2022-08-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateField(null=True),
        ),
    ]
