# Generated by Django 4.1 on 2022-09-05 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_user',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 6, 16, 28, 76476, tzinfo=datetime.timezone.utc)),
        ),
    ]
