# Generated by Django 4.1 on 2022-09-05 12:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_alter_twitter_user_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitter_user',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 12, 43, 35, 346447, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Stalking_logsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2022, 9, 5, 12, 43, 35, 417956, tzinfo=datetime.timezone.utc))),
                ('new_following_twitter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_following_twitter_id', to='twitter.twitter_user')),
                ('stalking_twitter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stalking_twitter_id', to='twitter.twitter_user')),
            ],
        ),
    ]
